<?php
/**
 * Author:
 * Michael Kefeder
 * http://code.google.com/p/rcmail-thunderbird-labels/
 *
 * Thomas Payen
 * https://github.com/messagerie-melanie2/roundcube_plugins
 */

$labels = array();

$labels['labels'] = 'Labels';
$labels['labels settings'] = 'Messages labels';
$labels['labels list'] = 'Labels list';
$labels['label'] = 'Thunderbird labels';
$labels['add_label'] = 'Add label';
$labels['manage_labels'] = 'Manage labels';
$labels['remove_label'] = 'Delete label';

$labels['thunderbird_settings'] = 'Thunderbird preferences';
$labels['thunderbird_settings_infos'] = 'Copy/paste here Thunderbird settings of your labels to have same name and color (This will erase your previous labels settings)';

$labels['label0'] = 'No Label';
$labels['label1'] = 'Important';
$labels['label2'] = 'Work';
$labels['label3'] = 'Personal';
$labels['label4'] = 'To Do';
$labels['label5'] = 'Later';

$labels['labels_filter_placeholder'] = 'Labels filter';

