<?php
/**
 * Author:
 * Michael Kefeder
 * http://code.google.com/p/rcmail-thunderbird-labels/
 *
 * Thomas Payen
 * https://github.com/messagerie-melanie2/roundcube_plugins
 */

$labels = array();

$labels['labels'] = 'Étiquettes';
$labels['labels settings'] = 'Étiquettes des messages';
$labels['labels list'] = 'Liste des étiquettes';
$labels['label'] = 'Étiquettes du Courrielleur';
$labels['add_label'] = 'Ajouter une étiquette';
$labels['manage_labels'] = 'Gérer les étiquettes';
$labels['remove_label'] = 'Supprimer l\'étiquette';

$labels['thunderbird_settings'] = 'Configuration de Thunderbird';
$labels['thunderbird_settings_infos'] = 'Copiez/collez ici la configuration des étiquettes de Thunderbird pour avoir les mêmes étiquettes et couleurs. (ATTENTION: Cela va écraser toutes les étiquettes que vous aurez précédemment configurées)';

$labels['label0'] = 'Enlever toutes les &eacute;tiquettes';
$labels['label1'] = 'Important';
$labels['label2'] = 'Travail';
$labels['label3'] = 'Personnel';
$labels['label4'] = 'A faire';
$labels['label5'] = 'Plus tard';

$labels['labels_filter_placeholder'] = 'Filtrer les étiquettes';